In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)
element = a[1]
print(element)

[1 2 3]
2


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
element = matrix[1, 2]
print(element)

6


In [7]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [8]:
a = np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


In [9]:
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [10]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
a = np.linspace(0, 10, num=5,dtype=np.int64)
print(a)

[ 0  2  5  7 10]


In [13]:
a = np.ones(5, dtype=np.int64)
print(a)

[1 1 1 1 1]


In [18]:
arr = np.array([3, 5, 4, 2, 1])
print(arr)


[3 5 4 2 1]


In [19]:
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [17]:
arr = np.sort(arr)[::-1]
print(arr)


[5 4 3 2 1]


In [20]:
arr = np.delete(arr, 3)
print(arr)

[1 2 3 5]


In [21]:
arr = np.array([[4, 1, 3],
                [2, 6.5, 7],
                [10,23,6]])


In [22]:
sap_xep_theo_hang = np.sort(arr, axis=1) 
print(sap_xep_theo_hang)

[[ 1.   3.   4. ]
 [ 2.   6.5  7. ]
 [ 6.  10.  23. ]]


In [23]:
sap_xep_theo_cot = np.sort(arr, axis=0)
print(sap_xep_theo_cot)

[[ 2.   1.   3. ]
 [ 4.   6.5  6. ]
 [10.  23.   7. ]]


In [24]:
arr = np.array([[4, 1, 3],
                [2, 6.5, 7],
                [10,23,6]])

In [25]:
sap_xep_theo_hang = -np.sort(-arr, axis=1) 
print(sap_xep_theo_hang)

[[ 4.   3.   1. ]
 [ 7.   6.5  2. ]
 [23.  10.   6. ]]


In [27]:
sap_xep_theo_cot = -np.sort(-arr, axis=0)
print(sap_xep_theo_cot)

[[10.  23.   7. ]
 [ 4.   6.5  6. ]
 [ 2.   1.   3. ]]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
so_chieu = arr.ndim 
kich_thuoc = arr.size  
hinh_dang = arr.shape  

In [30]:
print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [31]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [33]:
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [34]:
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
reshaped_arr = reshaped_arr.flatten()
print(reshaped_arr)

[1 2 3 4 5 6]


In [36]:
arr = np.array([1, 2, 3, 4, 5])

In [37]:
sub_arr = arr[1:4] 
print(sub_arr)

[2 3 4]


In [38]:
sub_arr = arr[:-1]  
print(sub_arr) # xoá số phần tử từ cuôi

[1 2 3 4]


In [39]:
sub_arr = arr[-2:]  
print(sub_arr) # : ở sau thì lấy số pt từ cuối

[4 5]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [42]:
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [43]:
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng", total)

Tổng 15


In [44]:
avg = np.mean(arr)
print("Tính giá trị trung bình của mảng arr:", avg)

Tính giá trị trung bình của mảng arr: 3.0


In [45]:
max_value = np.max(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)

Giá trị lớn nhất trong mảng arr: 5


In [46]:
min_value = np.min(arr)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

Giá trị nhỏ nhất trong mảng arr: 1


In [47]:
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

Độ lệch chuẩn của mảng arr: 1.4142135623730951


In [48]:
variance = np.var(arr)
print("phương sai của mảng arr:", variance)

Phương sai của mảng arr: 2.0


In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [50]:
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của 2 mảng:", dot_product)

Tổng tích chập của 2 mảng: 32
